In [30]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import jieba

In [31]:
df =pd.read_csv("/content/drive/MyDrive/nlpfinaldata/Copy of censored.csv")

In [32]:
df.head()

,mkTL1pvXTN,这王某人与中国青年报怎么这么有缘啊。uRLOGZLR4： 原来是个大流氓,2012-01-07 22:29:56,2012-03-03 03:35:43.903155,True
0,m5PIm1JzG8,经常看到有代表四处调研，你代表的是哪个行业，就好好调研一下本行业的问题好不好？自己的工作都做...,2012-01-05 09:00:03,2012-01-30 21:36:44.229791,True
1,mJGNyWD5fj,刚在宝宝的书架上发现这本书，翻了一下，历史事实描述一派胡言。问宝宝，这本书的内容你们考试吗？...,2012-01-02 12:45:58,False,True
2,m3e5KqAhFh,应该找uRLOWL0ZX： 去影他相！新年流流揸公车出来行，仲要违章，真是岂有此理！,2012-01-03 18:15:24,2012-01-30 19:15:54.549843,True
3,mkTLyULvfH,崔永元：微博春晚节目——天津快板：竹板这么一打啊，啥也不能说，不能说食品，不能说动车，不能说...,2012-01-07 12:02:02,2012-02-28 11:08:24.583212,True
4,mCClThFL7F,两会修改婚姻法），打字员一疏忽，把一夫一妻打成打成一天一妻。人大会审议时普遍反映：就这条改得...,2012-01-05 19:32:32,2012-03-07 11:13:25.184388,True

In [33]:
col_names = ['Id',
             'tweet',
             'tweeted_date',
             'deleted_date',
             'label']
censored_data = pd.read_csv('/content/drive/MyDrive/nlpfinaldata/Copy of censored.csv', names=col_names)

censored_data

,Id,tweet,tweeted_date,deleted_date,label
0,mkTL1pvXTN,这王某人与中国青年报怎么这么有缘啊。uRLOGZLR4： 原来是个大流氓,2012-01-07 22:29:56,2012-03-03 03:35:43.903155,True
1,m5PIm1JzG8,经常看到有代表四处调研，你代表的是哪个行业，就好好调研一下本行业的问题好不好？自己的工作都做...,2012-01-05 09:00:03,2012-01-30 21:36:44.229791,True
2,mJGNyWD5fj,刚在宝宝的书架上发现这本书，翻了一下，历史事实描述一派胡言。问宝宝，这本书的内容你们考试吗？...,2012-01-02 12:45:58,False,True
3,m3e5KqAhFh,应该找uRLOWL0ZX： 去影他相！新年流流揸公车出来行，仲要违章，真是岂有此理！,2012-01-03 18:15:24,2012-01-30 19:15:54.549843,True
4,mkTLyULvfH,崔永元：微博春晚节目——天津快板：竹板这么一打啊，啥也不能说，不能说食品，不能说动车，不能说...,2012-01-07 12:02:02,2012-02-28 11:08:24.583212,True
...,...,...,...,...,...
39001,mSa8Yuyo0u,嘻嘻不见小秘书心不死啊,2012-03-09 17:27:19,2012-03-10 11:57:47.265013,True
39002,mhirA1zecI,转发微博,2012-03-09 17:45:06,2012-03-10 12:24:50.774500,True
39003,mf6W9ly7gW,uAHFPZPCY： 转发微博,2012-03-08 23:07:08,2012-03-10 12:24:50.774500,True
39004,mvibd0cYxe,关注。强烈关注。u0YUSDPAP： ukn： 莺歌海u02LFXFKE： uONPWA...,2012-03-08 10:53:41,2012-03-10 12:24:50.774500,True
39005,mtqirHCHYk,刘主任的观点： u02LFXFKE： 煤电厂风情小镇荒唐腐败u02LFXFKE： 中国各...,2012-03-05 10:19:05,2012-03-10 12:24:50.774500,True

In [34]:
censored=censored_data.drop(['Id', 'tweeted_date' ,'deleted_date'], axis = 1)

In [35]:
censored.head()

                                               tweet label
0              这王某人与中国青年报怎么这么有缘啊。uRLOGZLR4：  原来是个大流氓  True
1  经常看到有代表四处调研，你代表的是哪个行业，就好好调研一下本行业的问题好不好？自己的工作都做...  True
2  刚在宝宝的书架上发现这本书，翻了一下，历史事实描述一派胡言。问宝宝，这本书的内容你们考试吗？...  True
3      应该找uRLOWL0ZX： 去影他相！新年流流揸公车出来行，仲要违章，真是岂有此理！  True
4  崔永元：微博春晚节目——天津快板：竹板这么一打啊，啥也不能说，不能说食品，不能说动车，不能说...  True

In [54]:
set(censored['label'].values)

{'True', 'permission_denied'}

In [36]:
uncensored_data = pd.read_csv('/content/drive/MyDrive/nlpfinaldata/Copy of not_censored.csv',nrows=70000)
uncensored_data.head()

,mCClUNCqwe,转发微博,2012-01-03 02:02:27,False,False.1
0,mRsOcOLTlc,uK3RXUYW3： u0AGMTTVD： ！！！！！！！！,2012-01-03 01:17:39,False,False
1,mH44qG6iUm,求一切順利,2012-01-03 01:15:36,False,False
2,mZmwFtOdVX,想要uK3RXUYW3： ukn： 全都想要啊QAQ,2012-01-03 01:12:55,False,False
3,mQkLJSl8bf,ukn： uMLLV3ZCO： 转发微博,2012-01-03 01:10:42,False,False
4,mnzrsoGWNN,ukn： ukn： 吐槽点太多 ukn： 竟然没被吐槽ukn： 偷笑ukn： 而且...,2012-01-03 01:09:54,False,False

In [37]:
col_names = ['Id',
             'tweet',
             'tweeted_date',
             'deleted_date',
             'label']
uncensored_data = pd.read_csv('/content/drive/MyDrive/nlpfinaldata/Copy of not_censored.csv',nrows=70000, names=col_names)

uncensored_data

,Id,tweet,tweeted_date,deleted_date,label
0,mCClUNCqwe,转发微博,2012-01-03 02:02:27,False,False
1,mRsOcOLTlc,uK3RXUYW3： u0AGMTTVD： ！！！！！！！！,2012-01-03 01:17:39,False,False
2,mH44qG6iUm,求一切順利,2012-01-03 01:15:36,False,False
3,mZmwFtOdVX,想要uK3RXUYW3： ukn： 全都想要啊QAQ,2012-01-03 01:12:55,False,False
4,mQkLJSl8bf,ukn： uMLLV3ZCO： 转发微博,2012-01-03 01:10:42,False,False
...,...,...,...,...,...
69995,mgYszJ02od,面对打学生的老师，家长怎么办？,2012-01-02 20:41:16,False,False
69996,mH44qiWfCs,发表了博文 《面对打学生的老师，家长怎么办？》 下面是一位朋友在我微博上的留言： 三月...,2012-01-02 20:37:29,False,False
69997,mL2ukAcJB6,很美！,2012-01-02 16:54:36,False,False
69998,mdZXczhCMj,为更简单更质朴的生活而努力！谢谢丫爸爸对园里活动的支持。,2012-01-02 16:48:54,False,False
69999,mU5j5pdNeJ,谢谢丫丫爸爸的美图。新年快乐！,2012-01-02 16:47:18,False,False

In [38]:
uncensored=uncensored_data.drop(['Id', 'tweeted_date' ,'deleted_date'], axis = 1)

In [55]:
set(uncensored['label'].values)

{False}

In [39]:
uncensored.head()

                             tweet  label
0                             转发微博  False
1  uK3RXUYW3： u0AGMTTVD：  ！！！！！！！！  False
2                            求一切順利  False
3      想要uK3RXUYW3： ukn：  全都想要啊QAQ  False
4           ukn：  uMLLV3ZCO：  转发微博  False

In [40]:
frames = [censored,uncensored]

data = pd.concat(frames)

In [53]:
set(data['label'].values)

{False, 'True', 'permission_denied'}

In [12]:
data.head()

                                               tweet label
0              这王某人与中国青年报怎么这么有缘啊。uRLOGZLR4：  原来是个大流氓  True
1  经常看到有代表四处调研，你代表的是哪个行业，就好好调研一下本行业的问题好不好？自己的工作都做...  True
2  刚在宝宝的书架上发现这本书，翻了一下，历史事实描述一派胡言。问宝宝，这本书的内容你们考试吗？...  True
3      应该找uRLOWL0ZX： 去影他相！新年流流揸公车出来行，仲要违章，真是岂有此理！  True
4  崔永元：微博春晚节目——天津快板：竹板这么一打啊，啥也不能说，不能说食品，不能说动车，不能说...  True

In [13]:
data.tail()

                                                   tweet  label
69995                                   面对打学生的老师，家长怎么办？   False
69996  发表了博文 《面对打学生的老师，家长怎么办？》  下面是一位朋友在我微博上的留言：   三月...  False
69997                                                很美！  False
69998                       为更简单更质朴的生活而努力！谢谢丫爸爸对园里活动的支持。  False
69999                                    谢谢丫丫爸爸的美图。新年快乐！  False

In [14]:
data.dtypes

tweet    object
label    object
dtype: object

In [15]:
data = data.astype(str)

In [16]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(data.label)
data['label'] = le.transform(data.label)

In [17]:
data

                                                   tweet  label
0                  这王某人与中国青年报怎么这么有缘啊。uRLOGZLR4：  原来是个大流氓      1
1      经常看到有代表四处调研，你代表的是哪个行业，就好好调研一下本行业的问题好不好？自己的工作都做...      1
2      刚在宝宝的书架上发现这本书，翻了一下，历史事实描述一派胡言。问宝宝，这本书的内容你们考试吗？...      1
3          应该找uRLOWL0ZX： 去影他相！新年流流揸公车出来行，仲要违章，真是岂有此理！      1
4      崔永元：微博春晚节目——天津快板：竹板这么一打啊，啥也不能说，不能说食品，不能说动车，不能说...      1
...                                                  ...    ...
69995                                   面对打学生的老师，家长怎么办？       0
69996  发表了博文 《面对打学生的老师，家长怎么办？》  下面是一位朋友在我微博上的留言：   三月...      0
69997                                                很美！      0
69998                       为更简单更质朴的生活而努力！谢谢丫爸爸对园里活动的支持。      0
69999                                    谢谢丫丫爸爸的美图。新年快乐！      0

[109006 rows x 2 columns]

In [27]:
data['label'].unique()

array([1, 2, 0])

In [18]:
X=data["tweet"]
y=data["label"]

In [20]:
#importing required packages
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [22]:
count_vectorizer = CountVectorizer(tokenizer=jieba.lcut)
X_train_count=count_vectorizer.fit_transform(X_train)

Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 2.520 seconds.
Prefix dict has been built successfully.

In [23]:
#defining model and fitting train data
model = MultinomialNB()
model.fit(X_train_count,y_train)##model traing took place here

MultinomialNB()

In [24]:
X_test_count=count_vectorizer.transform(X_test)
y_predict= model.predict(X_test_count)
y_predict

array([1, 0, 0, ..., 1, 1, 0])

In [25]:
#printing confusion matrix
from sklearn.metrics import confusion_matrix
matrix= confusion_matrix(y_test,y_predict)
matrix

array([[15442,  1955,     1],
       [ 1652,  8196,     0],
       [    6,     0,     0]])

In [26]:
#printing accuracy score
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_predict)

0.8673858799354176

In [ ]:
count_vectorizer = CountVectorizer(tokenizer=jieba.lcut)
x = count_vectorizer.fit_transform(X_train).toarray()
x_test = count_vectorizer.transform(X_test).toarray()

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train,y_train)

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import jieba
import numpy as np

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(tokenizer=jieba.lcut)

In [ ]:
X = count_vectorizer.fit_transform(data['tweet'].apply(lambda x: np.str_(x)))

Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.029 seconds.
Prefix dict has been built successfully.

In [ ]:
X.toarray()
pd.DataFrame(X.toarray())

In [ ]:
X=data["tweet"]
y=data["label"]

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
from sklearn import linear_model
clf = linear_model.LogisticRegression(C=1e40, solver='newton-cg')
fitted_model = clf.fit(X, y)

ValueError: ignored

In [ ]:
from sklearn.naive_bayes import CategoricalNB
clf = CategoricalNB()
clf.fit(X, y)

ValueError: ignored

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import jieba
import numpy as np

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(tokenizer=jieba.lcut)

In [ ]:
X = count_vectorizer.fit_transform(df[''].apply(lambda x: np.str_(x)))

Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.986 seconds.
Prefix dict has been built successfully.

In [ ]:
X.toarray()
pd.DataFrame(X.toarray())
count_vectorizer.get_feature_names()
pd.DataFrame(X.toarray(), columns=count_vectorizer.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,,0,00,007,00noreading,01,01052012,01059192848,01059193344,01064380428,...,ｃ,ｆ,ｎ,ｓ,ｗ,～,￢,￣,￥,勇
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
##after preprocessing
chinese_stopwords = ["、","。","〈","〉","《","》","一","一些","一何","一切","一则","一方面","一旦","一来","一样","一般","一转眼","七","万一","三","上","上下","下","不","不仅","不但","不光","不单","不只","不外乎","不如","不妨","不尽","不尽然","不得","不怕","不惟","不成","不拘","不料","不是","不比","不然","不特","不独","不管","不至于","不若","不论","不过","不问","与","与其","与其说","与否","与此同时","且","且不说","且说","两者","个","个别","中","临","为","为了","为什么","为何","为止","为此","为着","乃","乃至","乃至于","么","之","之一","之所以","之类","乌乎","乎","乘","九","也","也好","也罢","了","二","二来","于","于是","于是乎","云云","云尔","五","些","亦","人","人们","人家","什","什么","什么样","今","介于","仍","仍旧","从","从此","从而","他","他人","他们","他们们","以","以上","以为","以便","以免","以及","以故","以期","以来","以至","以至于","以致","们","任","任何","任凭","会","似的","但","但凡","但是","何","何以","何况","何处","何时","余外","作为","你","你们","使","使得","例如","依","依据","依照","便于","俺","俺们","倘","倘使","倘或","倘然","倘若","借","借傥然","假使","假如","假若","做","像","儿","先不先","光是","全体","全部","八","六","兮","共","关于","关于具体地说","其","其一","其中","其二","其他","其余","其它","其次","具体地说","具体说来","兼之","内","再","再其次","再则","再有","再者","再者说","再说","冒","冲","况且","几","几时","凡","凡是","凭","凭借","出于","出来","分","分别","则","则甚","别","别人","别处","别是","别的","别管","别说","到","前后","前此","前者","加之","加以","即","即令","即使","即便","即如","即或","即若","却","去","又","又及","及","及其","及至","反之","反而","反过来","反过来说","受到","另","另一方面","另外","另悉","只","只当","只怕","只是","只有","只消","只要","只限","叫","叮咚","可","可以","可是","可见","各","各个","各位","各种","各自","同","同时","后","后者","向","向使","向着","吓","吗","否则","吧","吧哒","含","吱","呀","呃","呕","呗","呜","呜呼","呢","呵","呵呵","呸","呼哧","咋","和","咚","咦","咧","咱","咱们","咳","哇","哈","哈哈","哉","哎","哎呀","哎哟","哗","哟","哦","哩","哪","哪个","哪些","哪儿","哪天","哪年","哪怕","哪样","哪边","哪里","哼","哼唷","唉","唯有","啊","啐","啥","啦","啪达","啷当","喂","喏","喔唷","喽","嗡","嗡嗡","嗬","嗯","嗳","嘎","嘎登","嘘","嘛","嘻","嘿","嘿嘿","四","因","因为","因了","因此","因着","因而","固然","在","在下","在于","地","基于","处在","多","多么","多少","大","大家","她","她们","好","如","如上","如上所述","如下","如何","如其","如同","如是","如果","如此","如若","始而","孰料","孰知","宁","宁可","宁愿","宁肯","它","它们","对","对于","对待","对方","对比","将","小","尔","尔后","尔尔","尚且","就","就是","就是了","就是说","就算","就要","尽","尽管","尽管如此","岂但","己","已","已矣","巴","巴巴","年","并","并且","庶乎","庶几","开外","开始","归","归齐","当","当地","当然","当着","彼","彼时","彼此","往","待","很","得","得了","怎","怎么","怎么办","怎么样","怎奈","怎样","总之","总的来看","总的来说","总的说来","总而言之","恰恰相反","您","惟其","慢说","我","我们","或","或则","或是","或曰","或者","截至","所","所以","所在","所幸","所有","才","才能","打","打从","把","抑或","拿","按","按照","换句话说","换言之","据","据此","接着","故","故此","故而","旁人","无","无宁","无论","既","既往","既是","既然","日","时","时候","是","是以","是的","更","曾","替","替代","最","月","有","有些","有关","有及","有时","有的","望","朝","朝着","本","本人","本地","本着","本身","来","来着","来自","来说","极了","果然","果真","某","某个","某些","某某","根据","欤","正值","正如","正巧","正是","此","此地","此处","此外","此时","此次","此间","毋宁","每","每当","比","比及","比如","比方","没奈何","沿","沿着","漫说","焉","然则","然后","然而","照","照着","犹且","犹自","甚且","甚么","甚或","甚而","甚至","甚至于","用","用来","由","由于","由是","由此","由此可见","的","的确","的话","直到","相对而言","省得","看","眨眼","着","着呢","矣","矣乎","矣哉","离","秒","竟而","第","等","等到","等等","简言之","管","类如","紧接着","纵","纵令","纵使","纵然","经","经过","结果","给","继之","继后","继而","综上所述","罢了","者","而","而且","而况","而后","而外","而已","而是","而言","能","能否","腾","自","自个儿","自从","自各儿","自后","自家","自己","自打","自身","至","至于","至今","至若","致","般的","若","若夫","若是","若果","若非","莫不然","莫如","莫若","虽","虽则","虽然","虽说","被","要","要不","要不是","要不然","要么","要是","譬喻","譬如","让","许多","论","设使","设或","设若","诚如","诚然","该","说","说来","请","诸","诸位","诸如","谁","谁人","谁料","谁知","贼死","赖以","赶","起","起见","趁","趁着","越是","距","跟","较","较之","边","过","还","还是","还有","还要","这","这一来","这个","这么","这么些","这么样","这么点儿","这些","这会儿","这儿","这就是说","这时","这样","这次","这般","这边","这里","进而","连","连同","逐步","通过","遵循","遵照","那","那个","那么","那么些","那么样","那些","那会儿","那儿","那时","那样","那般","那边","那里","都","鄙人","鉴于","针对","阿","除","除了","除外","除开","除此之外","除非","随","随后","随时","随着","难道说","零","非","非但","非徒","非特","非独","靠","顺","顺着","首先","︿","！","＃","＄","％","＆","（","）","＊","＋","，","０","１","２","３","４","５","６","７","８","９","：","；","＜","＞","？","＠","［","］","｛","｜","｝","～","￥"]
count_vectorizer_pre = CountVectorizer(stop_words=chinese_stopwords, tokenizer=jieba.lcut)
X1 = count_vectorizer_pre.fit_transform(df['text'].apply(lambda x: np.str_(x)))
X1.toarray()
pd.DataFrame(X1.toarray())
count_vectorizer.get_feature_names()
pd.DataFrame(X1.toarray(), columns=count_vectorizer_pre.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['借傥', '兼', '前', '唷', '啪', '啷', '喔', '天', '始', '漫', '然', '特', '竟', '莫', '见', '设', '达'] not in stop_words.
  % sorted(inconsistent)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,,0,00,007,00noreading,01,01052012,01059192848,01059193344,01064380428,...,＝,ｂ,ｃ,ｆ,ｎ,ｓ,ｗ,￢,￣,勇
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
##def count_texts(texts):
  count_vectorizer = CountVectorizer(tokenizer=jieba.lcut)
  # .fit_transfer TOKENIZES and COUNTS
  X = count_vectorizer.fit_transform(texts)
  X.toarray()
  pd.DataFrame(X.toarray())
  count_vectorizer.get_feature_names()
  pd.DataFrame(X.toarray(), columns=count_vectorizer.get_feature_names())

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words=chinese_stopwords, tokenizer=jieba.lcut, use_idf=False, norm='l1')
X3 = tfidf_vectorizer.fit_transform(df['text'].apply(lambda x: np.str_(x)))
pd.DataFrame(X3.toarray(), columns=tfidf_vectorizer.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['借傥', '兼', '前', '唷', '啪', '啷', '喔', '天', '始', '漫', '然', '特', '竟', '莫', '见', '设', '达'] not in stop_words.
  % sorted(inconsistent)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,,0,00,007,00noreading,01,01052012,01059192848,01059193344,01064380428,...,＝,ｂ,ｃ,ｆ,ｎ,ｓ,ｗ,￢,￣,勇
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.600000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9996,0.230769,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9997,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9998,0.200000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
vectorizer = TfidfVectorizer(use_idf=True, stop_words=chinese_stopwords, tokenizer=jieba.lcut)
X4 = vectorizer.fit_transform(df['text'].apply(lambda x: np.str_(x)))
pd.DataFrame(X4.toarray(), columns=tfidf_vectorizer.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['借傥', '兼', '前', '唷', '啪', '啷', '喔', '天', '始', '漫', '然', '特', '竟', '莫', '见', '设', '达'] not in stop_words.
  % sorted(inconsistent)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,,0,00,007,00noreading,01,01052012,01059192848,01059193344,01064380428,...,＝,ｂ,ｃ,ｆ,ｎ,ｓ,ｗ,￢,￣,勇
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.377324,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.252285,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.546638,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9996,0.208567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9997,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9998,0.096364,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0